{"uid":"6b333b94b48c8f43","name":"Demo failed test cases","fullName":"Search Functionality: Demo failed test cases","historyId":"ce7f5c9b51f1a8e229623049aeb7cdce","time":{"start":1727306477550,"stop":1727306479026,"duration":1476},"status":"failed","statusMessage":"AssertionError\n","statusTrace":"  File \"C:\\Python-Selenium\\Python_SeleniumBDD\\Python_Selenium\\venv1\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Python-Selenium\\Python_SeleniumBDD\\Python_Selenium\\venv1\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\testing\\steps\\login_feature.py\", line 40, in step_impl\n    assert False\n           ^^^^^\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"AssertionError\n","statusTrace":"  File \"C:\\Python-Selenium\\Python_SeleniumBDD\\Python_Selenium\\venv1\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Python-Selenium\\Python_SeleniumBDD\\Python_Selenium\\venv1\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\testing\\steps\\login_feature.py\", line 40, in step_impl\n    assert False\n           ^^^^^\n","steps":[{"name":"Given : Navigate to Home page","time":{"start":1727306477551,"stop":1727306478816,"duration":1265},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"stepsCount":0,"attachmentStep":false},{"name":"Then Fail the test case","time":{"start":1727306478816,"stop":1727306478816,"duration":0},"status":"failed","statusMessage":"AssertionError\n","statusTrace":"  File \"C:\\Python-Selenium\\Python_SeleniumBDD\\Python_Selenium\\venv1\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Python-Selenium\\Python_SeleniumBDD\\Python_Selenium\\venv1\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\testing\\steps\\login_feature.py\", line 40, in step_impl\n    assert False\n           ^^^^^\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":0,"hasContent":true,"stepsCount":0,"attachmentStep":false}],"attachments":[{"uid":"cc7302ff27f16176","name":"failure_screenshot","source":"cc7302ff27f16176.png","type":"image/png","size":49946}],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":1,"hasContent":true,"stepsCount":2,"attachmentStep":false},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"feature","value":"Search Functionality"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"6b333b94b48c8f43.json","parameterValues":[]}